// examples/vue-starter/src/templates/invoice-reference/components/InvoiceReferenceWatermark.vue
<script setup lang="ts">
defineProps<{
  text: string;
}>();
</script>

<template>
  <div
    style="
      transform: rotate(-24deg);
      font-size: 52px;
      font-weight: 700;
      letter-spacing: 0.08em;
      color: rgba(79, 70, 229, 0.14);
      text-transform: uppercase;
    "
  >
    {{ text }}
  </div>
</template>

// packages/create-dfactory/templates/react/src/templates/invoice-reference/components/InvoiceReferenceWatermark.tsx
export function InvoiceReferenceWatermark(props: { text: string }) {
  return (
    <div
      style={{
        transform: "rotate(-24deg)",
        fontSize: "52px",
        fontWeight: 700,
        letterSpacing: "0.08em",
        color: "rgba(79, 70, 229, 0.14)",
        textTransform: "uppercase"
      }}
    >
      {props.text}
    </div>
  );
}
