// examples/vue-starter/src/templates/invoice-reference/components/InvoiceReferencePagination.vue
<script setup lang="ts">
import { AvoidBreakInside } from "@dfactory/pdf-primitives-vue";

defineProps<{
  pageNumberToken: string;
  totalPagesToken: string;
}>();
</script>

<template>
  <AvoidBreakInside
    style="
      width: 100%;
      padding: 4px 16px 8px;
      font-size: 9px;
      color: #64748b;
      display: flex;
      justify-content: space-between;
    "
  >
    <span>DFactory Reference Pagination Layer</span>
    <span>Page {{ pageNumberToken }} of {{ totalPagesToken }}</span>
  </AvoidBreakInside>
</template>

// packages/create-dfactory/templates/react/src/templates/invoice-reference/components/InvoiceReferencePagination.tsx
import { AvoidBreakInside } from "@dfactory/pdf-primitives-react";

export function InvoiceReferencePagination(props: {
  pageNumberToken: string;
  totalPagesToken: string;
}) {
  return (
    <AvoidBreakInside
      style={{
        width: "100%",
        padding: "4px 16px 8px",
        fontSize: "9px",
        color: "#64748b",
        display: "flex",
        justifyContent: "space-between"
      }}
    >
      <span>DFactory Reference Pagination Layer</span>
      <span>
        Page {props.pageNumberToken} of {props.totalPagesToken}
      </span>
    </AvoidBreakInside>
  );
}
