// packages/create-dfactory/templates/react/src/templates/invoice-reference/components/InvoiceReferencePagination.tsx
export function InvoiceReferencePagination(props: {
  pageNumberToken: string;
  totalPagesToken: string;
  markerClassPreview: string;
}) {
  return (
    <div
      className={props.markerClassPreview}
      style={{
        width: "100%",
        padding: "4px 16px 8px",
        fontSize: "9px",
        color: "#64748b",
        display: "flex",
        justifyContent: "space-between"
      }}
    >
      <span>DFactory Reference Pagination Layer</span>
      <span>
        Page {props.pageNumberToken} of {props.totalPagesToken}
      </span>
    </div>
  );
}

// packages/create-dfactory/templates/vue/src/templates/invoice-reference/components/InvoiceReferencePagination.vue
<script setup lang="ts">
defineProps<{
  pageNumberToken: string;
  totalPagesToken: string;
  markerClassPreview: string;
}>();
</script>

<template>
  <div
    :class="markerClassPreview"
    style="
      width: 100%;
      padding: 4px 16px 8px;
      font-size: 9px;
      color: #64748b;
      display: flex;
      justify-content: space-between;
    "
  >
    <span>DFactory Reference Pagination Layer</span>
    <span>Page {{ pageNumberToken }} of {{ totalPagesToken }}</span>
  </div>
</template>
