// packages/create-dfactory/templates/react/src/templates/invoice-reference/components/InvoiceReferenceHeader.tsx
export function InvoiceReferenceHeader(props: {
  title: string;
  invoiceNumber: string;
  generatedAtToken: string;
}) {
  return (
    <div
      style={{
        width: "100%",
        padding: "0 14px",
        fontSize: "9px",
        color: "#475569",
        display: "flex",
        justifyContent: "space-between",
        alignItems: "center"
      }}
    >
      <span>{props.title}</span>
      <span>{props.invoiceNumber}</span>
      <span>{props.generatedAtToken}</span>
    </div>
  );
}

// packages/create-dfactory/templates/vue/src/templates/invoice-reference/components/InvoiceReferenceHeader.vue
<script setup lang="ts">
defineProps<{
  title: string;
  invoiceNumber: string;
  generatedAtToken: string;
}>();
</script>

<template>
  <div
    style="
      width: 100%;
      padding: 0 14px;
      font-size: 9px;
      color: #475569;
      display: flex;
      justify-content: space-between;
      align-items: center;
    "
  >
    <span>{{ title }}</span>
    <span>{{ invoiceNumber }}</span>
    <span>{{ generatedAtToken }}</span>
  </div>
</template>
